### klem's starship config

# Get editor completions based on the config schema, i.e. for editing in VSCode, etc.
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt formatting
format = """
[](red)\
$os\
$username\
[](bg:lavender fg:red)\
$directory\
[](fg:lavender bg:sky)\
$git_branch\
$git_status\
[](fg:sky bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:mauve)\
$docker_context\
$conda\
[](fg:mauve bg:flamingo)\
$time\
[ ](fg:flamingo)\
$line_break$character"""

# Color palette
palette = "catppuccin_mocha"

[os]
disabled = false
style = "bg:red fg:surface0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:surface0"
style_root = "bg:red fg:surface0"
format = '[ $user ]($style)'

[directory]
style = "fg:surface0 bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:sky"
format = '[[ $symbol $branch ](fg:surface0 bg:sky)]($style)'

[git_status]
style = "bg:sky"
format = '[[($all_status$ahead_behind )](fg:surface0 bg:sky)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:surface0 bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $context) ](fg:pink bg:mauve)]($style)'

[conda]
style = "bg:mauve"
format = '[[ $symbol( $environment) ](fg:pink bg:mauve)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:flamingo"
format = '[[  $time ](fg:surface0 bg:flamingo)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[♥ ](bold fg:pink)'
error_symbol = '[♥ ](bold fg:mauve)'
vimcmd_symbol = '[](bold fg:pink)'
vimcmd_replace_one_symbol = '[](bold fg:peach)'
vimcmd_replace_symbol = '[](bold fg:peach)'
vimcmd_visual_symbol = '[](bold fg:lavender)'

## Color palette tables

# Catppuccin Mocha
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"